### PR TITLE
Made it possible to use variables for `speaker` in `say` statements.

### PR DESCRIPTION
**Pull request by labiker**
Made it possible to use `variables` for `speaker` in say statements.

```
setVar:t=Tom;
setVar:s=Sam;
t:It's not Sam, it's Tom.
s:It's not Tom, it's Sam.
```

image

image

### CODE REVIEW

**Comment by MakinoharaShoko** [comment]
必须有一种方式区分是变量插值还是普通的字符串，否则容易造成混乱

**Comment by labiker** [comment]
@MakinoharaShoko 
Has been modified to the following usage.

```
setVar:heroine=WebGAL;
setVar:egine=WebGAL;

{heroine}:欢迎使用 {egine}！这是一款全新的网页端视觉小说引擎。
```

**Comment by MakinoharaShoko** [comment]
不仅仅是 say，让变量插值可以对任何语句的 content 和 option 中的 value 生效，会更好。

**Comment by labiker** [comment]
If you need to use `{` or `}` characters directly, you can use escape characters.

```
\{heroine\}:欢迎使用 \{egine\}！这是一款全新的网页端视觉小说引擎。
```

The previous sentence will not be considered as having variable interpolation and will be escaped as ↓

```
{heroine}:欢迎使用 {egine}！这是一款全新的网页端视觉小说引擎。
```

**Comment by labiker** [comment]
> 不仅仅是 say，让变量插值可以对任何语句的 content 和 option 中的 value 生效，会更好。

Modification completed.

**Comment by MakinoharaShoko** [comment]
@labiker added test and did some refactor, please check.

**Comment by labiker** [comment]
@MakinoharaShoko 
Thank you for your modification. There is no problem after modification.

**Comment by labiker** [comment]
It might be better if the following effects can be achieved?

```
setVar:myFunc=changeBg;
setVar:bg=bg.png;
{myFunc}:{bg} -next;
```

**Comment by MakinoharaShoko** [comment]
> It might be better if the following effects can be achieved?
> 
> ```
> setVar:myFunc=changeBg;
> setVar:bg=bg.png;
> {myFunc}:{bg} -next;
> ```

I don't think this is necessary, it's unlikely that there will be a need for it.

**Pull request merged**
