### PR TITLE
Se_bug_fix

### PR DESCRIPTION
**Pull request by generalfreed**
An error occurred because the value being set to the volume property of HTMLMediaElement exceeded the allowable range (between 0 and 1).
Fixed.

### CODE REVIEW

**Comment by generalfreed** [comment]
@labiker
確認お願いします！

**Comment by MakinoharaShoko** [comment]
I believe the key to this issue lies in the fact that when the state table in Redux is overwritten by the state from local storage, it can mistakenly be written as undefined due to the existence of previous versions of local user data (previous versions may not have a state field like "se volume"). It is important to handle such issues with caution.

**Comment by generalfreed** [comment]
@MakinoharaShoko @labiker
I think it would be better to use redux-persist to store data related to volume in localStorage or AsyncStorage storage write and read it.

**Comment by MakinoharaShoko** [comment]
Due to the fact that the archives are stored in the Redux state, if we use redux-persist, we do not have full control over the timing of storage read and write operations, which may result in a performance decrease. Currently, storage read and write operations are only triggered when entering the archive interface or changing options. However, redux-persist is automatic, which is not conducive to our performance optimization efforts.

**Pull request merged**
