### PR TITLE
Live2D and Background filter Add

### PR DESCRIPTION
**Pull request by generalfreed**
・Change the color and placement of options
・Added Live2D function
　Please execute the following command
　npm install pixi-live2d-display

If you want to test Live2D functionality, please download the Live2D Hiyori Momose sample data below.
* Download sample data that is not video version https://www.live2d.com/zh-CHS/download/sample-data/

Unzip hiyori_pro_jp.zip and store everything in the figure folder Call hiyori_pro_t11.model3.json with visual editor

・Add background filter function
　Please execute the following command
　npm install pixi-filters@4.2.0

If you want to enable a background filter, select it from Filters in the visual editor. By first setting a similar background with no filters, you can see the changes in real time.

### CODE REVIEW

**Comment by MakinoharaShoko** [comment]
The Live2D part can be kept, but the filters support will be refactored as part of Effect so that the timeline animation can be applied to filters as well. filters refactoring will start soon, I'll pick a filter as an example and then you can add more filters.

**Comment by MakinoharaShoko** [comment]
Of course, the reconstructed filters can work for both the rendering and the background

**Comment by generalfreed** [comment]
Can you take a look at conflicts?
 If it's too difficult, I remove the background filter function.

**Comment by MakinoharaShoko** [comment]
It might not be a good practice to add a live2DMotion field directly to the state table, since you need to consider the case where there are many live2D images present at the same time, I think it would be possible to transform this field into an object with a key corresponding to the position or id of the standup and a value corresponding to the motion.

**Comment by MakinoharaShoko** [comment]
> 

It wasn't very difficult, I just needed to set up a special effects field to handle more filters, and after I finished this refactoring, I was able to add a lot of filters in a very simple way, and for performance optimization reasons, filters are only added to the specified container when they need to be used. Otherwise, if we had to support hundreds of filters later, performance would be terrible.

**Comment by MakinoharaShoko** [comment]
In order to improve the center point shift caused by scale, the position adjustment of the stand or background is changed from adjusting the sprite position to adjusting the container position, so that the center point of the container is in the correct position.

**Comment by MakinoharaShoko** [comment]
image
As you can see, a lot has been modified here.

**Comment by generalfreed** [comment]
The center and scale of Live2D were aligned while debugging.
I will check it.

**Comment by MakinoharaShoko** [comment]
Therefore, in general, the changes that need to be made are summarized as follows:
1. use a new way to adjust the position of live2D models.
2. wait until the WebGALPixiContainer has been modified before adding filters.
3、motion uses an object to describe the state, the key is the target (position or id), the value is the name of the motion. Also, the way the motion is switched may need to be modified to avoid the impact on the live2D model already added to the stage when switching. It seems a bit strange to have to reset the model after each motion switch.

**Pull request closed without merging**
