### PR TITLE
Add filter function

### PR DESCRIPTION
**Pull request by generalfreed**
Add filter
・DotFilter
・ReflectionFilter
・GlitchFilter
・RGBFilter
・GodrayFilter

pixi-filters version 5 is not compatible with pixi6.
Specify v4.2.0 corresponding to pixi6.
https://github.com/pixijs/filters/releases

### CODE REVIEW

**Comment by generalfreed** [comment]
image

**Comment by MakinoharaShoko** [comment]
WebGALPixiContainer has a new section on filters, including how to remove a filter. please refer to the oldFilm section for slight modifications.

**Comment by MakinoharaShoko** [comment]
```typescript
  /**
   * old film filter
   * @private
   */
  private getOrCreateOldFilmFilter(createMode = true) {
    const blurFilterFromMap = this.containerFilters.get('oldFilm');
    if (blurFilterFromMap) {
      return blurFilterFromMap;
    } else {
      if (createMode) {
        const oldFilm = new OldFilmFilter();
        this.addFilter(oldFilm);
        this.containerFilters.set('oldFilm', oldFilm);
        return oldFilm;
      } else return null;
    }
  }
  public get oldFilm(): number {
    if (this.getOrCreateOldFilmFilter(false)) return 1;
    return 0;
  }

  public set oldFilm(value: number) {
    /**
     * 如果是0，就移除这个滤镜
     */
    if (value === 0) {
      this.removeFilter('oldFilm');
    } else this.getOrCreateOldFilmFilter();
  }

  private addFilter(filter: PIXI.Filter) {
    if (this.filters) {
      this.filters.push(filter);
    } else {
      this.filters = [filter];
    }
  }

  private removeFilter(name: string) {
    const filter = this.containerFilters.get(name);
    if (filter) {
      const index = (this?.filters ?? []).findIndex((e) => e === filter);
      if (this.filters) {
        this.filters.splice(index, 1);
        this.containerFilters.delete(name);
      }
    }
  }
```

**Comment by MakinoharaShoko** [comment]
For the live2D part, please refer to the solution for the standup part to handle the location, and verify that the save-read file can restore the live2D model correctly. for the motion part, you can use it as a field in the state table of type {[targetKey:string]:string}, and write a custom React hook to listen to this state and get the specified I plan to design a special data structure to handle this, and to support saving the state of the motion to prevent redundant motion modifications. Modifying motion can be done as a new command setMotion.

**Comment by generalfreed** [comment]
#WebGALPixiContainer has a new section on filters, including how to remove a filter. please refer to the oldFilm section for slight modifications.
https://github.com/MakinoharaShoko/WebGAL/commit/70032f84f865228c7f0110811bbd271c338acabb
refer to this source and I fix it

**Comment by MakinoharaShoko** [comment]
> > WebGALPixiContainer has a new section on filters, including how to remove a filter. please refer to the oldFilm section for slight modifications.
> 
> [70032f8](https://github.com/MakinoharaShoko/WebGAL/commit/70032f84f865228c7f0110811bbd271c338acabb) refer to this source and I fix it

Looking forward for your commit.

**Comment by generalfreed** [comment]
Fixed.

**Pull request merged**
